### ISSUE TITLE
opam v2. sandboxing

### ISSUE THREAD

**Issue by vzaliva** [fblanqui/color#12]
Current package install procedure is incompatible with opam2 sandboxing and it could not be installed unless sandboxing is disabled:

```
# path        ~/.opam/4.07.0/.opam-switch/build/coq-color.1.5.0                              
# command     ~/.opam/opam-init/hooks/sandbox.sh build make -f Makefile.coq install          
# exit-code   2
# env-file    ~/.opam/log/coq-color-62270-a71bb4.env                                         
# output-file ~/.opam/log/coq-color-62270-a71bb4.out                                         
### output ###
# [...]
# install: mkdir /Users/lord/.opam/4.07.0/lib/coq/user-contrib/CoLoR: Operation not permitted
# install: mkdir /Users/lord/.opam/4.07.0/lib/coq/user-contrib/CoLoR: Operation not permitted
```

I think the problem is that it attempts to create destination directory, while under sandboxing this directory is already created and the sandbox extends to its content only.

**Comment by fblanqui** [comment]
It seems to be a problem in coq_makefile because CoLoR is using the Makefile generated by coq_makefile. I added the issue https://github.com/coq/coq/issues/8593 in Coq.

**Comment by vzaliva** [comment]
The workaround is to disable sandboxing either by `opam init --disable-sandboxing` for new opam or `opam init --reinit --disable-sandboxing` for existing

**Comment by Zdancewic** [comment]
The workaround for installing coq-flocq turned out to be temporarily removing the sandbox wrapping lines from ~/.opam/config.  I'll make a note of this in the installation instructions.

**Comment by fblanqui** [comment]
Problem solved in https://github.com/coq/opam-coq-archive/commit/5531d05d4f1d32815c1b2b6397b23403c3751bdc by adding an opam install command. So, no need for disabling sandboxing.
