### ISSUE TITLE
new release for Coq-8.9

### ISSUE THREAD

**Issue by vzaliva** [fblanqui/color#16]
Current OPAM release is coq-color-1.5.0 which does not work with Coq-8.9. It is not just OPAM package version check. The source code in release tarball does not compile with Coq-8.9.

However, the current state of this git repository compiles under Coq-8.9 without any changes.

It would be great to make a new release based on the current git master and push it into OPAM. My project depends on coq-color and I could not upgrade to Coq-8.9 because of this problem. I will be glad to help with the release if needed.

**Comment by fblanqui** [comment]
Hi Vadim. I was waiting for https://github.com/coq/bignums/issues/17 to 
be solved. I'm going to do this tomorrow.

Le 09/02/2019 à 22:31, Vadim Zaliva a écrit :

**Comment by fblanqui** [comment]
It's done!

**Comment by vzaliva** [comment]
thanks!
