### ISSUE TITLE
Vbuild_spec_obligation_5

### ISSUE THREAD

**Issue by vzaliva** [fblanqui/color#22]
I am porting some old proofs for 8.9 to 8.10.2 and immediately stumbled upon a problem. Consider this lemma:

```
Require Import CoLoR.Util.Vector.VecUtil.
Import VectorNotations.
Open Scope vector_scope.
Lemma Vbuild_1 B gen:
  @Vbuild B 1 gen = [gen 0 (Arith.Lt.lt_0_Sn 0)].
Proof.
  unfold Vbuild.
  cbn.
  apply Vcons_eq.
  split.
  - apply f_equal, Peano_dec.le_unique.
  - reflexivity.
Qed.
```

After cbn step in Coq-8.9 the goal looks like:

```
[gen 0 (VecUtil.Vbuild_spec_obligation_4 gen eq_refl)] = [gen 0 (PeanoNat.Nat.lt_0_succ 0)]
```

However, with Coq 8.10.2 I get:

```
eq_rect 1 (fun H : nat => vector B H)
[gen 0 (VecUtil.Vbuild_spec_obligation_4 eq_refl)] 1
(VecUtil.Vbuild_spec_obligation_5 eq_refl) = [gen 0 (PeanoNat.Nat.lt_0_succ 0)]
```

The problem traced back (with help from @zoickx) to the following changeset:

https://github.com/fblanqui/color/compare/f7a4c8a444c54e220c3055a4f4c68a1f214f0a4b..44b6693d71f8ac72b2610f46d97b3c766ffddea5?diff=unified#diff-3802eaffee5b7512dcba958bc4eea1e4

It looks like the following workaround helps:

```
Lemma Vbuild_1 B gen:
  @Vbuild B 1 gen = [gen 0 (Arith.Lt.lt_0_Sn 0)].
Proof.
  unfold Vbuild.
  cbn.

  assert (h : VecUtil.Vbuild_spec_obligation_5 (eq_refl 1) = eq_refl 1).
  apply eq_unique.
  rewrite h. cbn.

  apply Vcons_eq.
  split.
  - apply f_equal, Peano_dec.le_unique.
  - reflexivity.
Qed.
```

But it is frankly a bit ugly. Specifically, because it depends on the auto-generated lemma name.
In my project, I use `Vbuild` a lot and this workaround have to be used a lot. Perhaps there is a better way?

**Comment by Blaisorblade** [comment]
(Caveat: As an outsider, seeing this from the Coq forum) Can't you use `Vbuild_head` instead? (https://github.com/fblanqui/color/compare/f7a4c8a444c54e220c3055a4f4c68a1f214f0a4b..44b6693d71f8ac72b2610f46d97b3c766ffddea5?diff=unified#diff-3802eaffee5b7512dcba958bc4eea1e4R1780). And can you similarly fix your other uses? The statements of those lemmas has not changed.

IME and IMHO, definitions written using tactics (such as `Vbuild`) such *not* be unfolded directly, but only through unfolding lemmas — direct unfolding is fragile (as you notice) and should be considered as breaking an *abstraction barrier*. Somehow, even this commit is enough to make your code ill-typed: https://github.com/fblanqui/color/pull/23/commits/7573658b9454640274fd3895f994d4163ac422dd (but I'll fix that).
Ideally, `Vbuild` should be made opaque, either via `Opaque` or via stronger means if possible.

The author of such a definition should provide such lemmas, and the clients should restrict themselves to using those lemmas. Whether the provided lemmas are sufficient to your needs, not sure, but I don't see anything missing.

Program's successor, coq-Equations, even provides automatic support for making definitions opaque and providing unfolding lemmas.

**Comment by fblanqui** [comment]
Hi @vzaliva . is the solution proposed by @Blaisorblade satisfying for you?

**Comment by vzaliva** [comment]
By the solution do you mean his pull request or his suggestion to never unfold `Vbuild`?

As to PR, I will try his patch (need to compile custom build of coq-color with it). It might help.

As to not unfolding, I am not so sure. `Vbuild_spec` provides a clean inductive definition that could be used in induction proofs, etc. I will need to see if I can rework all my proofs to use helper lemmas to avoid unfolding it. I little feel uneasy about working with such a basic definition that should not be unfolded.

**Comment by Blaisorblade** [comment]
@vzaliva You can ignore my PR, it’s meant for a different problem.

> Vbuild_spec provides a clean inductive definition that could be used in induction proofs, etc.

For an even cleaner inductive definition, maybe you want an unfolding lemma closer to (untested, but inspired from the statements of `Vbuild_head` and `Vbuild_tail`):
```coq
Lemma Vbuild_unfold n gen : @Vbuild n gen =
    match n with
      | 0 => Vnil
      | S p => Vcons (gen 0 (lt_O_Sn n)) (@Vbuild p (fun i ip => gen (S i) (lt_n_S ip)))
     end.
```
and then rewrite with `Vbuild_unfold` instead of unfolding. It seems provable from the given lemmas, tho I’d consider exposing it in the library.

**Comment by Blaisorblade** [comment]
(And in general, alternative unfolding lemmas could make sense).

> I little feel uneasy about working with such a basic definition that should not be unfolded.

Since I’m nobody, I should have mentioned it’s the style in various libraries, starting from math-comp, exactly to avoid the issue you face (implementation details leaking to clients). Otherwise, to enable unfolding `Vbuild_spec` without exposing users to generated code, somebody would have to write the full proof term by hand and keep it stable, which doesn’t sound like a great idea...

**Comment by vzaliva** [comment]
@Blaisorblade thanks for your comments suggestions! They are really appreciated!

I think the issue boils down to more philosophical question of to what extend library definitions should be opaque. For example, should users ever try to unfold `List.fold_left` from the standard library or only use the library provided lemmas?

**Comment by Blaisorblade** [comment]
`fold_left` is transparent *and* hand-written. This one is written using `Program`, so should be opaque. More complicated cases might exist.
Marking `Vbuild_spec` as Opaque would clarify things, if possible, but that's a matter of style and not my call.

**Comment by vzaliva** [comment]
To avoid unfolding and dealing with obligations I found this lemma helpful:

```
Lemma Vbuild_Sn (B : Type) (n : nat) (gen : forall i : nat, i < S n -> B):
  @Vbuild B (S n) gen = (gen 0 (Nat.lt_0_succ n))
                          ::
                          Vbuild (fun (i : nat) (ip : i < n) => gen (S i) (lt_n_S ip)).
Proof.
  rewrite <- Vbuild_head.
  rewrite <- Vbuild_tail.
  apply VSn_eq.
Qed.
```

Maybe it should be part of the library.

**Comment by fblanqui** [comment]
Hi @vzaliva . Please have a look at the last version (d5e10eee218116c466dfa878ee3d997abe7ca247) and tell me if it solves your problem.

**Comment by vzaliva** [comment]
At this point I've solved my problem by switching to use `Vbuild_Sn` lemma everywhere I used unfolding before. The new definition of Vbuild looks much cleaner, but now it uses convoy pattern which could complicate proofs a little. I do not have a strong preference either way.

**Comment by vzaliva** [comment]
I have a workaround (`Vbuild_Sn`) which does the same as unfolding `Vbuild_spec` without having to deal with the obligation. I also see @fblanqui proposed change to `Vbuild` definition which will make this problem obsolete. Hence I am closing this issue with thanks @fblanqui and @Blaisorblade for the help!
