### ISSUE TITLE
Coq 8.8 support

### ISSUE THREAD

**Issue by vzaliva** [fblanqui/color#3]
The `coq-released` OPAM repository contains the version of `coq-color` incompatible with the latest Coq release (Coq-8.8):

```
$ opam install coq-color
The following dependencies couldn't be met:
  - coq-color -> coq-bignums < 8.8~
```

**Comment by fblanqui** [comment]
Should be fixed by https://github.com/coq/opam-coq-archive/commit/f11043a00b19be07fa3ab1ad9c877134977f9d59.
