### ISSUE TITLE
Links to old GForge opam versions

### ISSUE THREAD

**Issue by clarus** [fblanqui/color#38]
Hello,

The links in the opam packages for versions prior to 1.8 do not seem to work anymore. For example, in https://github.com/coq/opam-coq-archive/blob/master/released/packages/coq-color/coq-color.1.7.0/opam there is a link to https://gforge.inria.fr/frs/download.php/file/38188/color.1.7.0.tar.gz which returns "403 Forbidden" on my computer.

**Comment by fblanqui** [comment]
Thank you for the issue. It should be fixed in https://github.com/coq/opam-coq-archive/commit/587e1b037181488c2988bb441730dfef998d1939.

**Comment by clarus** [comment]
OK thanks!
