### ISSUE TITLE
Please make your project compile with -w "+compatibility-notation"

### ISSUE THREAD

**Issue by Zimmi48** [fblanqui/color#9]
Please make your project compile with `-w "+compatibility-notation"` to prepare for the Coq 8.9 release. We would appreciate if this could be done ASAP. If you have trouble doing so, please raise your concern at coq/coq#8383.

**Comment by fblanqui** [comment]
My Coq Makefile is built using coq_makefile and a generated _CoqProject. 
What option should I give to coq_makefile or add into _CoqProject for 
doing that?


Le 02/09/2018 à 12:21, Théo Zimmermann a écrit :

**Comment by fblanqui** [comment]
@Zimmi48 : I added https://github.com/coq/coq/issues/8392.

**Comment by Zimmi48** [comment]
Thanks for raising this problem @fblanqui!

**Comment by fblanqui** [comment]
Well, it's just that the variable is not added into Makefile.coq but in Makefile.coq.conf (it is not documented). I'm on the way to fix your request soon.

**Comment by Zimmi48** [comment]
@fblanqui Did you manage to make warnings fatal then? How did you do?

**Comment by fblanqui** [comment]
For the moment, I'm just trying to do what you asked as follows:

diff --git a/Makefile b/Makefile
index ca0b4e1..0b8faa1 100644
--- a/Makefile
+++ b/Makefile
@@ -21,7 +21,7 @@ time: Makefile.coq
 
 config Makefile.coq:
        echo -R . $(LIBNAME) $(VFILES) > _CoqProject
-       coq_makefile -f _CoqProject > Makefile.coq
+       coq_makefile COQEXTRAFLAGS = '-w \"+compatibility-notation\"' -f _CoqProject -o Makefile.coq
 
I still have some warnings. For instance, I have many of these warnings:

COQC Term/Lambda/LTerm.v
File "./Term/Lambda/LTerm.v", line 494, characters 2-69:
Warning: Notation _ [=] _ was already used. [notation-overridden,parsing]

Warning: Notation _ =v _ was already used. [notation-overridden,parsing]
File "./MatrixInt/AArcticBasedInt.v", line 58, characters 2-14:
Warning: Trying to mask the absolute name "ABI"!
[masking-absolute-name,deprecated]

Do you want all warnings to be fatal?

Thanks for giving me some hints on how to eliminate these warnings.

**Comment by Zimmi48** [comment]
>Do you want all warnings to be fatal?

Not for now, thanks. Of course, it would be better if we could eliminate all warnings, but compatibility-notation is the only one that is needed at the moment.

>Thanks for giving me some hints on how to eliminate these warnings.

Do not hesitate to open new issues when these warnings do not give sufficiently detailed explanations of what the problem is and how to solve it.

**Comment by Zimmi48** [comment]
Note that commit b043ef8e8d2811cd53e28827fff2634cd5fe4eaa didn't change anything, I still see:
```
File "./Term/WithArity/ATrsNorm.v", line 76, characters 26-37:
Warning: nat_compare is Nat.compare [compatibility-notation,deprecated]
COQC Term/Lambda/LTerm.v
```
